### ISSUE TITLE
Project admin, milestones, and roadmap

### ISSUE THREAD

**Issue by christian-oreilly** [niivue/ipyniivue#50]
This "issue" is more of an administrative log to help us manage the initial development of this project. We can close it and move this to other more appropriate management tools down the line. For now, I suggest the following target for ipyniivue-experimental based on the AnyWidget approach:

Develop a widget allowing us to replicate, in JupyterNotebook, with Python code, the demo already prepared for NiiVue. The functionalities must be usable from the Python side (i.e., we don't want just to be able to display JS demos in Jupyter Notebooks; we want to be able to implement them in Python using the JS wrapper). I suggest we implement these are different notebooks and cross them off the following list when done:

- [ ] [Basic multiplanar](https://niivue.github.io/niivue/features/basic.multiplanar.html)
- [ ] [Sync mesh](https://niivue.github.io/niivue/features/sync.mesh.html)
- [ ] [Bidirectional Sync](https://niivue.github.io/niivue/features/sync.bidirectional.html)
- [ ] [Color maps for voxels](https://niivue.github.io/niivue/features/colormaps.html) and [meshes](https://niivue.github.io/niivue/features/colormaps.mesh.html)
- [ ] [Background masks overlays](https://niivue.github.io/niivue/features/mask.html)
- [ ] [Alpha and asymmetric statistical thresholds](https://niivue.github.io/niivue/features/alphathreshold.html)
- [ ] [Test images](https://niivue.github.io/niivue/features/test_images.html)
- [ ] [Drag and drop](https://niivue.github.io/niivue/features/draganddrop.html)
- [ ] [Select font](https://niivue.github.io/niivue/features/selectfont.html)
- [ ] [Connectome](https://niivue.github.io/niivue/features/connectome.html) [Connectome API](https://niivue.github.io/niivue/features/connectome.api.html)
- [ ] [Minimal user interface with menus](https://niivue.github.io/niivue/features/ui.html) see [niivue-ui for a more advanced user interface](https://github.com/niivue/niivue-ui)
- [ ] [Meshes (GIfTI, FreeSurfer, MZ3, OBJ, STL, legacy VTK)](https://niivue.github.io/niivue/features/meshes.html)
- [ ] [Mesh MatCaps](https://niivue.github.io/niivue/features/mesh.matcap.html)
- [ ] [Mesh Statistics](https://niivue.github.io/niivue/features/mesh.stats.html)
- [ ] [Mesh layers (GIfTI, FreeSurfer, MZ3)](https://niivue.github.io/niivue/features/mesh.layers.html)
- [ ] [Load Mesh Layers](https://niivue.github.io/niivue/features/mesh.loader.html)
- [ ] [4D mesh time series (GIfTI, FreeSurfer, MZ3)](https://niivue.github.io/niivue/features/mesh.4D.html)
- [ ] [annot mesh atlases](https://niivue.github.io/niivue/features/mesh.atlas.html) and [GIFTI mesh atlases](https://niivue.github.io/niivue/features/mesh.atlas.gii.html) and [MGH mesh atlases](https://niivue.github.io/niivue/features/mesh.atlas.mgh.html)
- [ ] [GIfTI Meshes with NIfTI2 Curvature](https://niivue.github.io/niivue/features/mesh.curv.html)
- [ ] Anti-Aliasing: faster (off) or better (on)
- [ ] Auto-select [Mesh](https://niivue.github.io/niivue/features/mesh.freesurfer.html)   [Voxel](https://niivue.github.io/niivue/features/vox.aaAUTO.html)
- [ ] OFF (faster) [Mesh](https://niivue.github.io/niivue/features/mesh.freesurfer.aaOFF.html)   [Voxel](https://niivue.github.io/niivue/features/vox.aaOFF.html)
- [ ] ON (better) [Mesh](https://niivue.github.io/niivue/features/mesh.freesurfer.aaON.html)   [Voxel](https://niivue.github.io/niivue/features/vox.aaON.html)
- [ ] [FreeSurfer mask editing](https://niivue.github.io/niivue/features/freesurfer.html)
- [ ] [FreeSurfer point sets](https://niivue.github.io/niivue/features/pointset.html)
- [ ] [4D mesh time series (CIFTI-2)](https://niivue.github.io/niivue/features/cifti.4D.html)
- [ ] [Tractography (TCK, TRK, TRX, VTK)](https://niivue.github.io/niivue/features/tracts.html)
- [ ] [Tractography groups (TRX)](https://niivue.github.io/niivue/features/tracts.group.html)
- [ ] [Advanced tractography (TCK, TRK, TRX, VTK)](https://niivue.github.io/niivue/features/tracts2.html)
- [ ] [4D Time series data (fMRI, DTI, ASL, etc) using thumbnail for rapid loading](https://niivue.github.io/niivue/features/timeseries.html)
- [ ] [4D Time series data (fMRI, DTI, ASL, etc) initially showing only the first volumes for rapid loading](https://niivue.github.io/niivue/features/timeseries2.html)
- [ ] [AFNI volumes](https://niivue.github.io/niivue/features/afni.html)
- [ ] [BrainVoyager meshes](https://niivue.github.io/niivue/features/brainvoyager.html)
- [ ] [x3d meshes](https://niivue.github.io/niivue/features/x3d.html)
- [ ] [Clip planes](https://niivue.github.io/niivue/features/clipplanes.html)
- [ ] [Drawing](https://niivue.github.io/niivue/features/draw2.html)
- [ ] [Drawing user interface](https://niivue.github.io/niivue/features/draw.ui.html)
- [ ] [Torso regions](https://niivue.github.io/niivue/features/torso.html)
- [ ] [Carotid Artery-Computed Tomographic Angiography Scoring](https://niivue.github.io/niivue/features/cactus.html)
- [ ] [Voxel atlas](https://niivue.github.io/niivue/features/atlas.html)
- [ ] [Sparse voxel atlas](https://niivue.github.io/niivue/features/atlas.sparse.html)
- [ ] [Modulation](https://niivue.github.io/niivue/features/modulate.html)
- [ ] [Multiplanar Layout (Auto, Column, Grid, Row)](https://niivue.github.io/niivue/features/layout.html)
- [ ] [Modulation of scalar volumes](https://niivue.github.io/niivue/features/modulateScalar.html)
- [ ] [Modulation of AFNI statistics](https://niivue.github.io/niivue/features/modulateAfni.html)
- [ ] [Fixed canvas size](https://niivue.github.io/niivue/features/fixedsize.html)
- [ ] [Segmented image with named labels](https://niivue.github.io/niivue/features/segment.html)
- [ ] [Mosaics](https://niivue.github.io/niivue/features/mosaics.html)
- [ ] [Advanced mosaics](https://niivue.github.io/niivue/features/mosaics2.html)
- [ ] [World space](https://niivue.github.io/niivue/features/worldspace.html)
- [ ] [Advanced world space](https://niivue.github.io/niivue/features/worldspace2.html)
- [ ] [Images with shear](https://niivue.github.io/niivue/features/shear.html)
- [ ] [Multiuser basic 3D](https://niivue.github.io/niivue/features/multiuser.3d.html)
- [ ] [Multiuser Time Series](https://niivue.github.io/niivue/features/multiuser.timeseries.html)
- [ ] [Multiuser color maps](https://niivue.github.io/niivue/features/multiuser.imageoptions.html)
- [ ] [Multiuser meshes](https://niivue.github.io/niivue/features/multiuser.meshes.html)
- [ ] [User scripting](https://niivue.github.io/niivue/features/scripts.html)
- [ ] [Shiny volume rendering](https://niivue.github.io/niivue/features/shiny.volumes.html)
- [ ] [Dragging callbacks](https://niivue.github.io/niivue/features/dragCallback.html)
- [ ] [Voxels with complex numbers](https://niivue.github.io/niivue/features/complex.html)
- [ ] Additive [voxels](https://niivue.github.io/niivue/features/additive.voxels.html) and [mesh](https://niivue.github.io/niivue/features/additive.mesh.html) as well as [negative colormaps](https://niivue.github.io/niivue/features/additive.mesh.negative.html)
- [ ] [DICOM Manifest](https://niivue.github.io/niivue/features/dicom.manifest.html)
- [ ] [Load a document](https://niivue.github.io/niivue/features/document.load.html)
- [ ] [Download a document with 3D render](https://niivue.github.io/niivue/features/document.3d.html)
- [ ] [Download a document with drawing](https://niivue.github.io/niivue/features/document.drawing.html)
- [ ] [Download a document with meshes](https://niivue.github.io/niivue/features/document.meshes.html)
- [ ] [Save a scene as HTML](https://niivue.github.io/niivue/features/save.html.html)
- [ ] [Save a scene with custom HTML](https://niivue.github.io/niivue/features/save.custom.html.html)
- [ ] [Show labels](https://niivue.github.io/niivue/features/labels.html)

Besides ensuring these functionalities (and by integrating as notebooks ran by the CI on PR, ensuring that there is no code regression on these functionalities), I think we need to target the following objectives:
- [ ] Every public class, function, class method,  and class attribute has a doc string following pydocstyle
- [ ] The code is PEP8 compliant the linting is automatically checked and enforced through CI on every PR 
- [ ] The documentation is automatically generated and pushed to a doc website (see hooks implemented for ipyniivue)
- [ ] Test coverage above 90%

Final objective:
- [ ] Publication of a paper on this package.

**Comment by christian-oreilly** [comment]
@bcalford I think we can check out the Drawing examples from that list, right? Please go ahead and check any other examples from the list above that you think we are already covering.

**Comment by AnthonyAndroulakis** [comment]
This list is up to date currently, yes, and I update it whenever I work on the project. I've been unable to join the past few meetings due to work conflicts, but I'll try to make more updates to the ipyniivue project.
